### ISSUE TITLE
使用相对路径传入文件会报错

### ISSUE THREAD

**Issue by TimerZz007** [alwaystest18/hostCollision#3]
报错：
[FTL] file open fail: 
![image](https://github.com/alwaystest18/hostCollision/assets/64236661/d37d6e18-d0cd-400c-897f-b4c6f2dcba37)

**Comment by alwaystest18** [comment]
看起来是df uf参数前面没有加-，导致指定文件没有成功导致的，你用-df -uf再试下看看
