### ISSUE TITLE
碰撞只会检测文件中的最后一个

### ISSUE THREAD

**Issue by andrewgogogo** [alwaystest18/hostCollision#6]
碰撞只会检测urls.txt和hosts.txt文件中的最后一个URL或域名。

**Comment by andrewgogogo** [comment]
![image](https://github.com/alwaystest18/hostCollision/assets/91301016/baf9587a-8197-45d5-8328-d8b42403aeba)

**Comment by alwaystest18** [comment]
你把两个文本的内容顺序换一换再试试，我之前的测试没有出现过这种情况，可能是凑巧

**Comment by andrewgogogo** [comment]
尝试过很多次，都是同样的情况，应该是循环的BUG。

**Comment by alwaystest18** [comment]
之前有一个windows下换行符的bug，刚刚修复了，试下最新版本

**Comment by alwaystest18** [comment]
如果问题得到解决，请关闭需求
